### PR TITLE
[feature] add feature for filter by keywords

### PR DESCRIPTION
**Pull request by abdullahtariq1171**
Added feature to filter logs by keywords

https://monosnap.com/file/7aYsbmeCf8Xf2pXSN12FNZIOagJIU0

I am not confident on prop names though `searchKeywords`, `logFilter`. Happy to change if you suggest something better.

### CODE REVIEW

**Comment by abdullahtariq1171** [comment]
I will update readme once we decide on props names. :D

**Comment by abdullahtariq1171** [comment]
hello @samdenty99 a friendly ping!

**Comment by samdenty99** [comment]
Awesome thanks! :fire:

**Comment by samdenty99** [comment]
Live on [2.8.5](https://www.npmjs.com/package/console-feed)

**Pull request merged**
